// ローカルストアへの操作。GUI からも CLI からもここだけを通す（FR-11）。
//
// 実体は packages/core/src/store/repo.ts。CLI（packages/cli）も同じ実装を使う。
// ここは Electron から既存の相対 import（'../shared/repo.js'）を変えずに済ませるための再 export のみ。

export {
  type Project,
  type PaperInput,
  type RankedPaper,
  type SurveyReport,
  yearFromPublishedAt,
  BLEND_SUMMARY_WEIGHT,
  BLEND_CHUNK_WEIGHT,
  blendScore,
  createProject,
  getProject,
  listProjects,
  updateTitle,
  setProjectRoot,
  setLastRunId,
  parseSearchTerms,
  setLastSearchTerms,
  updateSummary,
  setManuscript,
  listChunks,
  getChunkEmbedding,
  setChunkEmbedding,
  upsertPapers,
  listUnscored,
  countUnscoredMissingFulltext,
  listPapersNeedingFulltext,
  setPaperPdfUrl,
  setPaperFulltext,
  getPaperFulltextRow,
  listPapersMissingAuthors,
  fillPaperAuthors,
  saveScore,
  listRanked,
  countUnscored,
  makeBibtexKey,
  addToLibrary,
  listLibrary,
  upsertSurveyReport,
  listSurveyReports,
  getSurveyReport,
  listPapersForRun,
  reportsMissingTrend,
} from '@ai-research/core';
